### ISSUE TITLE
Allow cleanup recipies to run even if some recipie failed

### ISSUE THREAD

**Issue by amarao** [casey/just#1902] opened 2024-02-14 13:32 UTC
*It was asked in #1582  and closed because requestor found a partial solution for his problem*

There is a common pattern:

* span resource (e.g. VM)
* run deployment/test
* remove resource

This can be implemented  in Just, but only for happy path (test OK). If test fails, recipe fails, and resource is not removed.

This behavior is often implemented in CI servers (e.g. github Actions), with 'on_fail' or 'always' attribute for the cleanup job.

It can be done in CI, but Just is really cool and I love to use it for most things for local-first development, and this is feature I miss a lot.

This feature should allow to mark some of the subsequent dependencies as 'run even if there was error in prior recipes'.

Why solution from #1582 is not enough. It works only for bash (and we may want to run it for other interpreters, `parallel`, `python`, `ansible`, etc), and it does not allow to run recipes (which may be pretty big and be written in different languages).

E.g. like this:

```
create:
  touch virtual_machine

deploy:
  echo deploying

# I used !! to show '&& cleanup' which runs even if all other jobs fails
test: create deploy !! cleanup
  echo test failed
  /bin/false

cleanup:
  rm virtual_machine
```

Expected output:

```bash
$ just test

touch virtual_machine
echo deploying
deploying
echo test failed
test failed
/bin/false
error: Recipe `test` failed on line 9 with exit code 1. Continue to run cleanup
rm virtual_machine
error: Recipe `test` failed on line 9 with exit code 1
```

(error is repeated twice to have error to be the last line on the output)

**Comment by casey** [comment] 2024-02-14 20:36
I'm not sure I understand why `foo: bar || cleanup` doesn't work. In the output above, `rm virtual_machine` runes. Am I missing something?

**Comment by VladimirMarkelov** [comment] 2024-02-15 06:31
> I'm not sure I understand why foo: bar || cleanup doesn't work

Is it implemented already? I tried it on Windows (copy-pasted the example from the first comment and replaced `!!` with `||`:

```
>just --version
just 1.24.0

> just -f t.just
error: Unknown start of token:
 ——▶ t.just:8:21
  │
8 │ test: create deploy || cleanup
  │                     ^
```

**Comment by amarao** [comment] 2024-02-15 09:02
> I'm not sure I understand why `foo: bar || cleanup` doesn't work. In the output above, `rm virtual_machine` runes. Am I missing something?

`||` would work absolutely fine, but it's not implemented yet.

I think both are fine (`||` and `-&&`), but `||` has a bit of ambiguity, because in bash `do_left || do_right` will run `do_right` only if `do_left` failed.  But a cleanup recipe must run on both success and failure. 

May be it should three selectors:

* Run right if left success
* Run right if left failed
* Run right ignoring right status (bash analogue is `;`)
* (fourth option is to "never run right" is trivial and doesn't need additional syntax, '#' works fine)

... I think, adding both  '|| ' and ';' would make Just more universal and powerful tool.

**Comment by casey** [comment] 2024-02-15 20:57
Lol whoops, I forgot that `||` hasn't been implemented yet. Agree about `;`, that sounds good. I think this is a dupe of #1582, feel free to open an issue for `;`.

**Closed as completed by casey** 2024-02-15 20:57 UTC
