### ISSUE TITLE
update version on macports

### ISSUE THREAD

**Issue by jstrong-tios** [casey/just#502] opened 2019-10-24 22:07 UTC
Hey,

I am a longtime user and am pitching my office to use just. I went to install the macports version (since this would allow much easier adoption in this case) and was so confused: 

```console
$ sudo port install -s just
Warning: The macOS 10.14 SDK does not appear to be installed. Ports may not build correctly.
Warning: You can install it as part of the Xcode Command Line Tools package by running `xcode-select --install'.
--->  Computing dependencies for just
--->  Fetching distfiles for just
--->  Attempting to fetch just-0.2.0.tar.gz from https://github.com/casey/just/releases/download/0.2.0
--->  Attempting to fetch just-0.2.0.tar.gz from https://distfiles.macports.org/just
--->  Verifying checksums for just
--->  Extracting just
--->  Configuring just
--->  Building just
--->  Staging just into destroot
--->  Installing just @0.2.0_0
--->  Activating just @0.2.0_0
--->  Cleaning just
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
$ /opt/local/bin/just --help
Usage: gmake [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  --eval=STRING               Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-apple-darwin18.0.0
Report bugs to <bug-make@gnu.org>
```

(the `-s` in flag in `port install` forces building from source). 

Is this a really old version of just? The github releases don't even go back that far. From what I gather from searching issues there was once a dependency on make?

In any event, would it be possible to update the macports listing to the current version? (While searching, came across the [last time](https://trac.macports.org/ticket/50579) it was updated, which was a while ago).

Thanks in advance for any assistance you can provide, and for your work on a great program I use every day!

**Comment by casey** [comment] 2019-10-27 02:21
It is definitely an old version of just! Long ago, `just` was just a shell-script that wrapped make. (That version is actually still here, in [extras/just.sh](https://github.com/casey/just/blob/master/extras/just.sh).)

I'm the maintainer of the `just` macports port, and I tried a while ago to update the port to the new rust version, but I gave up after running into issues, I think which were caused by rust support in macports being quite new.

I just gave updating the port another shot, and I managed to do it this time, mostly by furiously copy-pastaïng from the `ripgrep`'s portfile.

I opened the PR [here](https://github.com/macports/macports-ports/pull/5632) so hopefully I didn't mess anything up and it gets merged soon. I'll leave this issue open until it gets merged, and I confirm that it's visible in the port tree.

I don't use macports anymore, so it's unlikely that I'll do a good job with keeping the port up to date. If any macports users would like to try to keep it up to date, do feel free to do so!

**Comment by casey** [comment] 2019-10-27 02:21
Also, thank you for the kinds words ^_^ I'm glad you find `just` useful!

**Comment by casey** [comment] 2019-10-28 09:18
Version 0.4.4 should now be available in macports, merged in [this PR](https://github.com/macports/macports-ports/pull/5632), and I just did a `port selfupdate`, and got the new version.

**Closed as completed by casey** 2019-10-28 09:18 UTC
Labels: distribution

**Comment by jstrong-tios** [comment] 2019-10-28 12:58
Thank you!
