### ISSUE TITLE
invocation_directory fails on Windows (pwsh)

### ISSUE THREAD

**Issue by glucas** [casey/just#585] opened 2020-01-28 21:29 UTC
Running in pwsh on Windows with this justfile: 

    set shell := ["pwsh", "-NoProfile", "-c"]

    pwd:
      @Write-Host {{invocation_directory()}}

produces an error:

    just
    error: Call to function `invocation_directory` failed: Error getting shell path: Error converting shell path: Error executing process: The system cannot find the file specified. (os error 2)
      |
    4 |   @Write-Host {{invocation_directory()}}
      |                 ^^^^^^^^^^^^^^^^^^^^

It would be great if this function could be supported on powershell.

**Comment by casey** [comment] 2020-01-29 01:37
Hi glucas, thanks for reporting this, this is definitely a bug.

The issue is that the implementation [directory implementation](https://github.com/casey/just/blob/1d084f1d4e0dbca366318337def98721c40c93fd/src/function.rs#L49) on Windows calls `cygpath`, which is only available when running under cygwin.

This used to be okay, because the only way to get Just to work under Windows was to run under cygwin, but now that shells are pluggable, that's no longer the case.

This is a somewhat thorny issue. `to_shell_path` is used because when running under windows but using `sh`, we need to convert between the path returned by system calls to something that `sh` can understand. However in this case, the shell is not `sh`, so we need to leave those paths alone.

I'm not 100% sure what the best way to solve this is. Ideally we would know if unix and/or windows paths could be used in the current environment, and only do the conversion if we have to.

I think as a quick fix, I'm inclined to just return the given path if `cygpath` isn't present. I opened #586, which does this.

If you have rust installed and you're comfortable doing so, could you see if the patch in #586 does the trick? If not that's okay, I'll just have to find another way of testing.

**Comment by casey** [comment] 2020-01-29 02:03
(I just merged #586 so it's in master.)

**Comment by runeimp** [comment] 2020-01-29 23:05
@casey couldn't the active shell for the recipe determine which path should be passed? If the OS is Windows but the recipe is using `sh` via shebang or other shell setting method then you'd use the appropriate path processor?

Hm, maybe that's not best. Cygwin, MSYS, and WSL (Windows Subsystem for Linux) use different conversions for drive letter to path. So you probably couldn't just check the shell but need to know the subsystem as well. Maybe if the OS is Windows and the shell is `sh` and `cygpath` is not present then WSL (or one of it's many predecessors) is the subsystem. Or just check if `/cygdrive/c/windows/notepad.exe` (Cygwin), `/c/windows/notepad.exe` (MSYS), or `/mnt/c/windows/notepad.exe` (WSL) exists?

**Comment by casey** [comment] 2020-01-30 03:50
@runeimp I was kinda thinking about that, but my fear is that there is a large combination of environments and shells, and I'd be worried that trying to guess wouldn't be robust in general.

Breaking down environments:
- WSL: I think in this case, users will be using the linux binary, which doesn't convert paths, so things should work fine.
- Cygwin: The patch I landed will use `cygpath` if available, and fall back to using the path as-is, so this should work under cygwin.
- MSYS: If `cygpath` is available, then Just will try to use it, but the path will be wrong. If `cygpath` isn't found, it will fall back to using the path as-is, which may be an issue.

**Comment by glucas** [comment] 2020-01-31 18:14
This change works fine for me, thanks! I've never used rust but I installed it from scoop and did a cargo build without any trouble. Testing the built just.exe with the above example it works as expected. 

Just to be clear, I'm testing on Windows 10 in a pwsh shell (PowerShell Core, 6.2.4) and using 'set shell' as described above. I don't have cygwin on this box and don't have sh on my path.

**Comment by casey** [comment] 2020-01-31 20:20
@glucas Awesome, glad to hear it!

The current solution is a bit hacky (just pass the pass through as-is if cygwin isn't present), but until there's a combination of environment and shell in which it doesn't work, I think this is safe to close.

**Closed as completed by casey** 2020-01-31 20:20 UTC
Labels: bug

**Comment by runeimp** [comment] 2020-02-03 19:45
You can also test for environment variables to help identify WSL.

WSL, for instance, would have these two

```
WSL_DISTRO_NAME=Alpine
WSLENV=
```

When in Alpine Linux in WSL

**Comment by casey** [comment] 2020-02-06 21:52
@glucas I just cut [v0.5.8](https://github.com/casey/just/releases/tag/v0.5.8), so prebuilt binaries are now available on the releases page containing the fix.
