### ISSUE TITLE
`positional-arguments` does not work with set shell?

### ISSUE THREAD

**Issue by Cologler** [casey/just#1559] opened 2023-03-01 10:37 UTC
For

```
set positional-arguments

run args:
    @echo $@
```

Execute `just run 2023` print:

```
2023
```

---

For

```
set positional-arguments
set shell := ["pwsh", "-c"]

run args:
    @echo $@
```

Execute `just run 2023` print:

```
$@
run
2023
```

---

For

```
set positional-arguments
set shell := ["nu", "-c"]

run args:
    @echo $@
```

Execute `just run 2023` print:

```
Error: nu::parser::variable_not_found (link)

  × Variable not found.
   ╭─[source:1:1]
 1 │ echo $@
   ·      ─┬
   ·       ╰── variable not found
   ╰────

error: Recipe `run` failed on line 5 with exit code 1
```

Test on just 1.13.0.

**Comment by runeimp** [comment] 2023-03-04 04:49
This seems to be a duplicate of #1554

But also `Error: nu::parser::variable_not_found (link)` looks like Nu shell instead PowerShell. Is your default shell Nu? If so this might be another part of the same issue of simply using `set positional-arguments` with PowerShell Core. What operating system are you using?

**Comment by Cologler** [comment] 2023-03-04 05:12
> This seems to be a duplicate of #1554
> 
> But also `Error: nu::parser::variable_not_found (link)` looks like Nu shell instead PowerShell. Is your default shell Nu? If so this might be another part of the same issue of simply using `set positional-arguments` with PowerShell Core. What operating system are you using?

My mistake. I updated the last example.

The arguments should expand by just.exe, whatever my default shell and OS are.

**Comment by runeimp** [comment] 2023-03-06 18:02
Thanks for the clarification. So the `pwsh` example is definitely the same as I was experiencing in #1554. Nu shell is similar to PowerShell in that they are both object based shells instead of string based like the majority of other shells in existence. So might have something to do with a possible change in Just v1.13.0. As this was not an issue I'd seen prior using Just with PowerShell. Though it may have existed prior and I simply hadn't tried using `set positional-arguments` with PowerShell before. I seem to remember a little oddness with Nu shell but It's been a while since I played with that Shell and Just. Any thoughts @casey ?

**Comment by cspotcode** [comment] 2023-05-02 18:40
Pretty sure `nu` does not allow access to positionals via `$@`, `$args`, et al, you have to wrap your script in a function declaration: https://www.nushell.sh/book/scripts.html#parameterizing-scripts

**Comment by runeimp** [comment] 2023-05-03 20:36
@cspotcode As I understand it using `set positional-arguments` is an enhancement that preprocesses the `$@`, `$1`, `$2`, etc. tokens before handoff to the the shell. If `set positional-arguments` was not enabled then those tokens would absolutely have to be handled by the shell itself.

**Comment by cspotcode** [comment] 2023-05-03 20:50
No, `set positional-arguments` appends them to the argv array when invoking the shell, it doesn't do any preprocessing.

My writeup in #1592 goes into greater detail.

But you can experiment with the following justfile to understand the exact argv array that is being received by the target executable.

```
# Try running `just default hello world` and carefully inspect the output
set shell := ["python", "-c", "import sys; print(sys.argv)"]
set positional-arguments
default *args:
    foo bar baz "$@" "$1"
```
```
$ just default hello world
foo bar baz "$@" "$1"
['-c', 'foo bar baz "$@" "$1"', 'default', 'hello', 'world']
```

This proves that `just` is not preprocessing, it is passing the characters `$` and `@` to the shell within the argv array of strings.

**Comment by runeimp** [comment] 2023-05-03 20:55
Ah, that's a bummer  ☹️

**Comment by Cologler** [comment] 2024-10-01 05:11
Work on PowerShell Core 7.4 with `-cwa` options:

```
set positional-arguments
set shell := ["pwsh", "-cwa"]

run *args:
    python -c "import sys; print(sys.argv)" @($args[1..($args.Count - 1)])
```

Execute `just run 1 '2 3'` print:

```
['-c', '1', '2 3']
```

**Comment by casey** [comment] 2024-10-01 05:45
@Cologler That's super nice! This has been a longstanding limitation. Is `-cwa` a new option? If `-cwa` is widely available, we should probably update the readme to suggest using `-CommandWithArgs` instead of `-Command.

**Comment by Cologler** [comment] 2024-10-01 09:12
@casey `CommandWithArgs` is an experimental feature added in 7.4. 

Source: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.4

**Comment by casey** [comment] 2024-10-01 19:15
Gotcha. I added a note to the readme in #2404. I think this is "fixed" and can be closed, since there's a good workaround.

**Closed as completed by casey** 2024-10-01 19:15 UTC

**Comment by Cologler** [comment] 2024-10-01 20:20
@casey Unlike `$@` in sh, powershell must use `@($args[1..($args.Count - 1)])` to skip the first argument pass from just.

**Comment by casey** [comment] 2024-10-01 20:29
@Cologler Thanks! Updating the example in the readme to be more complete in #2405.
