### ISSUE TITLE
Add support for importing all justfiles in a directory

### ISSUE THREAD

**Issue by noahdotpy** [casey/just#1841] opened 2024-01-13 06:43 UTC
some syntax like `import '~/justfiles/*'` would be great to import all justfiles in ~/justfiles/

**Comment by casey** [comment] 2024-01-13 07:34
That seems pretty reasonable. Technically this would be backwards incompatible, but having paths with `*` in them is so rare that I think adding this is reasonable. I think `glob` and `globset` are both good options.

**Comment by pprkut** [comment] 2024-01-15 14:19
This looks like a duplicate of #1641

**Comment by casey** [comment] 2024-01-15 18:13
Oh, nice, you're right. Closing in favor of #1641.

**Closed as completed by casey** 2024-01-15 18:13 UTC
