### ISSUE TITLE
feature request: string interpolation outside of recipe/target

### ISSUE THREAD

**Issue by king6cong** [casey/just#357] opened 2018-09-22 03:07 UTC
something like this would be helpful:

```justfile
path = "/path/example/"
init_and_cd_path = "mkdir -p {{path}} && cd {{path}} &&"

recipe1:
    init_and_cd_path \
    do_something
```

**Comment by casey** [comment] 2018-09-23 21:43
I think this would be useful, although I'm not 100% sure, since that would make it difficult to insert a literal `{{` into a recipe.

**Comment by king6cong** [comment] 2018-09-25 02:26
I am not sure whether [The Two Flavors of Variables](https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html) in makefile is a good idea for this.

**Comment by casey** [comment] 2018-10-02 19:29
I'm not sure how others feel, but I personally find the two flavors of variables to be super confusing >_<

I think the way I would allow this would be some sort of string prefix, which turns on interpolation in strings, like python: 

```
path = "/path/example/"
init_and_cd_path = f"mkdir -p {{path}} && cd {{path}} &&"

recipe1:
    init_and_cd_path \
    do_something
```

**Comment by casey** [comment] 2019-05-29 04:38
If we do add f-string syntax, it should apply to backticks, like so:

```
VIM := `which nvim || which vim`

VIM_VERSION := f`{{VIM}} --version`
```

(See discussion in #448.)

**Comment by ngirard** [comment] 2020-02-26 16:01
FWIW, this is probably the feature I've been missing the most when using Just...

**Comment by casey** [comment] 2021-04-07 22:40
I think this is a dupe of #11, so closing in favor of that.

**Closed as completed by casey** 2021-04-07 22:40 UTC
Labels: enhancement
