### ISSUE TITLE
[Bug] Unable to call `just` with an alias for a different target platform

### ISSUE THREAD

**Issue by DeeGeeMan** [casey/just#1681] opened 2023-09-29 14:08 UTC
### Just Example:
```
[private]
alias rp := run-program
[private]
alias rt := run-tasks

[macos]
@run-tasks:
   echo "running tasks..."

@run-program:
  echo "running program...''
```
### Command:
`> just rp`

_Note: the above command throws an error in Linux_ 
```
error: Alias `rt` has an unknown target `run-tasks`
```

**Comment by DeeGeeMan** [comment] 2023-09-29 14:14
`just` should allow target platform attributes on `alias` too.

Example:
```
[private, macos]
alias rt := run-tasks
```

**Comment by casey** [comment] 2023-10-09 05:13
I think this is a duplicate of #1493, have a look.

**Closed as completed by casey** 2023-10-09 05:13 UTC
