### ISSUE TITLE
support os-specific aliases

### ISSUE THREAD

**Issue by woutervh** [casey/just#1904] opened 2024-02-15 17:14 UTC
When I have an os-specific recipe like this in my justfile,
this fails on Linux if there is no Linux-equivalent:

```
# install JanDeDobbeleer's OhMyPosh from the Microsoft Store
[windows]
install-ohmyposh:
    winget install --id JanDeDobbeleer.OhMyPosh --source winget

alias install-oh-my-posh := install-ohmyposh
```

Fails on Linux with just 1.23.0:
```
error: Alias `install-oh-my-posh` has an unknown target `install-ohmyposh`
    │ alias install-oh-my-posh := install-ohmyposh
    │       ^^^^^^^^^^^^^^^^^^
```

I can work around by creating  dummy linux-recipes.

**Comment by casey** [comment] 2024-02-15 20:55
We definitely want to support this. Dupe of #1493.

**Closed as completed by casey** 2024-02-15 20:55 UTC
