### ISSUE TITLE
Specifying a custom .env file to be loaded

### ISSUE THREAD

**Issue by heavelock** [casey/just#1101] opened 2022-02-15 15:35 UTC
Hi! 
I'm evaluating possibility of moving from make to just in our team. After learning that we cannot do inheritance/importing ( 😢 ) of justfiles, I was looking for some other solution to help me with developing commands that have if/else depending on type of a project we want to run commands for (we have a polyglot monorepo). 

Do you think that it would be possible to add a config value specifying which .env file to load? Or adding some more filetypes that would be attempted to be loaded, for example `.justenv`. 

I could try to do a PR if you give me a green light and some indications, I always wanted to learn Rust :)

**Comment by casey** [comment] 2022-02-15 20:39
I think this is a dupe of #945, let me know if I'm wrong!

Would something like:

```
set dotenv-filename := ".justenv"
```

Work? Because that would definitely be reasonable, and hopefully fairly simple, to add.

**Closed as completed by casey** 2022-02-15 20:39 UTC

**Comment by heavelock** [comment] 2022-02-16 07:42
Oh yes, that's a duplicate! Sorry for that!
