### ISSUE TITLE
`just --fmt`: includes are injected instead of formatted

### ISSUE THREAD

**Issue by katexochen** [casey/just#1764] opened 2023-12-15 07:03 UTC
Taking the example from the README

```just
# justfile
!include justfile.inc

a: b
  @echo A
```
```just
# justfile.inc
b:
  @echo B
```

executing the formatter as

```just
just --fmt --unstable --justfile justfile
```

will update the justfile and insert the content of the included file:

```just
# justfile

# justfile.inc
b:
    @echo B

a: b
    @echo A
```

which is unexpected. I think this should format the included file instead and keep the include statement.

**Comment by pprkut** [comment] 2024-01-15 14:24
Looks like a duplicate of #1585

**Closed as completed** 2024-01-15 14:47 UTC
