### ISSUE TITLE
Opaque error when conditional is missing an `else` block

### ISSUE THREAD

**Issue by nk9** [casey/just#1251] opened 2022-06-25 11:44 UTC
## Problem
Currently, when a `justfile` has this code:

```
TEST := if path_exists('/bin/bash') == "true" {"yes"}
```

The error is this:

```
error: Expected identifier, but found end of line
```

This doesn't say which identifier was expected, which makes it difficult to understand.

## Diagnosis
The conditional is parsed in [`parse_conditional`](https://github.com/casey/just/blob/a46be416991b83a16028becf724d4b382fd9559d/src/parser.rs#L429). The `else` is expected [here](https://github.com/casey/just/blob/a46be416991b83a16028becf724d4b382fd9559d/src/parser.rs#L449). This [`expect_keyword`](https://github.com/casey/just/blob/a46be416991b83a16028becf724d4b382fd9559d/src/parser.rs#L159) function looks like it is set up to provide a useful error:

```
    if expected == found {
      Ok(())
    } else {
      Err(identifier.error(CompileErrorKind::ExpectedKeyword {
        expected: vec![expected],
        found,
      }))
    }
```

However, this code is never run because the call to `self.expect()` on the first line of the function produces [its own, more generic error](https://github.com/casey/just/blob/a46be416991b83a16028becf724d4b382fd9559d/src/parser.rs#L144).

I don't have a good feel for what the right solution here is. Perhaps there really are situations where the `else` block of `expect_keyword` is actually being reached? I'm happy to help, but could use some direction at this point.

**Comment by casey** [comment] 2022-06-25 22:29
This is a dupe of #1236, but closing that in favor of this, because this issue has a better description.

I think that avoiding calling `self.expect(Identifier)?` would be good, and instead examining the next token manually to see if it's both an identifier and the expected keyword.

**Closed as completed** 2022-07-01 11:34 UTC
