### ISSUE TITLE
feat: evaluate nested variables

### ISSUE THREAD

**Issue by pixeleet** [casey/just#1365] opened 2022-10-09 17:27 UTC
Imagine the following:
```
a := 'x'
b: = 'y'
c: = '{{a}} & {{b}}`
```

Expectation: 
`x & y`

Actual:
`{{a}} & {{b}}`

Test case:
```rust
test! {
  name:     evaluate_nested,
  justfile: "
    a := 'x'
    b := 'y'
    c := '{{a}} & {{b}}'
  ",
  args:   ("--evaluate", "c"),
  stdout: "x & y",
}
```

Is there some technical limitation preventing evaluating nested variables? 
Given some pointers would be happy to take a crack at it.

**Comment by casey** [comment] 2022-10-09 17:58
Closing as a duplicate of #11.

There's no technical limitation, it just hasn't been implemented yet. And you can see by the issue number, it's a longstanding request!

I think the best way to implement this is with a special syntax that turns on interpolations inside strings, probably just python's f-string syntax, i.e. `f"{{foo}}"`. This would make it a backwards compatible change, whereas just starting to interpret variables within strings would be a breaking change.

I would start by checking out #822, which is a partial implementation, with a bunch of good discussion. You might be able to use it as a basis, or at least get some inspiration.

**Closed as completed by casey** 2022-10-09 17:58 UTC
