### ISSUE TITLE
Run processes in parallel and wait

### ISSUE THREAD

**Issue by mortoray** [casey/just#676] opened 2020-09-05 12:58 UTC
It would be nice if basic parallel processing was added. Consider this target:

```
dev-watch game:
	#!/bin/bash
	just dev-game-assets {{game}} &
	just dev-client {{game}} &
	wait
```

I'm using bash to run these two targets in parallel and then wait for them both. In this case the processes don't terminate on their own (they are watching files and updating builds).  By using `wait` I'm able to press Ctrl+C to terminate all child processes.

As backgroung execution is already supported, I think the addition of `wait` might be enough -- as a keyword to indicate that the wrapping just should wait for all children to complete (and of course kill all children if interrupted).

**Comment by casey** [comment] 2020-09-05 19:54
I think this is a dupe of #626, commenting there.

**Closed as completed by casey** 2020-09-05 19:54 UTC
